const getUsersSchema = () => {
  const userSchema = {
    "table_name": "users",
    "table_display_name": "Users",
    "description": "users table description",
    "columns": [
      {
        "column_name": "id",
        "column_display_name": "Id",
        "column_type": "CHAR",
        "length": 32,
        "is_primary": true,
        "is_indexed": true,
        "is_user_added": false,
        "is_nullable": false,
        "description": null,
      },
      {
        "column_name": "identifier",
        "column_display_name": "Identifier",
        "column_type": "VARCHAR",
        "length": 255,
        "is_primary": false,
        "is_indexed": true,
        "is_user_added": false,
        "is_nullable": false,
        "description": null,
      },
      {
        "column_name": "identifier_type",
        "column_display_name": "Identifier Type",
        "column_type": "identifier_type",
        "default": "Email",
        "values": ["Email", "Mobile", "Username"],
        "is_primary": false,
        "is_indexed": true,
        "is_user_added": false,
        "is_nullable": false,
        "description": null,
      },
      {
        "column_name": "name",
        "column_display_name": "Name",
        "column_type": "VARCHAR",
        "default": "None",
        "length": 255,
        "is_primary": false,
        "is_indexed": true,
        "is_user_added": false,
        "is_nullable": true,
        "description": null,
      },
      {
        "column_name": "role",
        "column_display_name": "Role",
        "column_type": "role",
        "default": "Admin",
        "values": ["Admin", "Client"],
        "length": null,
        "is_primary": false,
        "is_indexed": true,
        "is_user_added": false,
        "is_nullable": false,
        "description": null,
      },
      {
        "column_name": "status",
        "column_display_name": "Status",
        "column_type": "status",
        "default": "Enabled",
        "values": ["Enabled", "Disabled", "Blacklisted"],
        "length": null,
        "is_primary": false,
        "is_indexed": true,
        "is_user_added": false,
        "is_nullable": false,
        "description": null,
      },
      {
        "column_name": "workflows",
        "column_display_name": "Workflows",
        "column_type": "TEXT[]",
        "default": null,
        "length": null,
        "is_primary": false,
        "is_indexed": true,
        "is_user_added": false,
        "is_nullable": true,
        "description": null,
      },
    ],
    table_type: "default",
  };
  return userSchema;
};

module.exports = {
  getUsersSchema,
}